In [ ]:
 import pandas as pd
 import numpy as nm
 import matplotlib.pyplot as plt


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Load the dataset
dataset = pd.read_csv('/content/drive/MyDrive/Office.csv')

In [ ]:
#Display the dataset output
dataset

,S/N,Name,Age,Department,Salary
0,1,osahon,29.0,Engineering,70000.0
1,2,Bob,NaN,Marketing,55000.0
2,3,Charlie,35.0,NaN,60000.0
3,4,David,42.0,Engineering,NaN
4,5,Eva,30.0,HR,48000.0
5,6,Frank,NaN,Finance,65000.0
6,7,Grace,27.0,Engineering,72000.0
7,8,Hannah,33.0,Marketing,NaN
8,9,Ian,40.0,NaN,58000.0
9,10,Jane,NaN,HR,NaN


In [ ]:
#Extracing independent variable
x=dataset.iloc[:,:-1].values
x

array([[1, 'osahon', 29.0, 'Engineering'],
       [2, 'Bob', nan, 'Marketing'],
       [3, 'Charlie', 35.0, nan],
       [4, 'David', 42.0, 'Engineering'],
       [5, 'Eva', 30.0, 'HR'],
       [6, 'Frank', nan, 'Finance'],
       [7, 'Grace', 27.0, 'Engineering'],
       [8, 'Hannah', 33.0, 'Marketing'],
       [9, 'Ian', 40.0, nan],
       [10, 'Jane', nan, 'HR'],
       [11, 'Kyle', 25.0, 'Finance']], dtype=object)

In [ ]:
#Extracting the depent variable
y = dataset.iloc[:,-1].values
y

array([70000., 55000., 60000.,    nan, 48000., 65000., 72000.,    nan,
       58000.,    nan,    nan])

In [ ]:
#Handling missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=nm.nan, strategy='mean')
imputer.fit(x[:,2:3])
x[:,2:3] = imputer.transform(x[:,2:3])
x

array([[1, 'osahon', 29.0, 'Engineering'],
       [2, 'Bob', 32.625, 'Marketing'],
       [3, 'Charlie', 35.0, nan],
       [4, 'David', 42.0, 'Engineering'],
       [5, 'Eva', 30.0, 'HR'],
       [6, 'Frank', 32.625, 'Finance'],
       [7, 'Grace', 27.0, 'Engineering'],
       [8, 'Hannah', 33.0, 'Marketing'],
       [9, 'Ian', 40.0, nan],
       [10, 'Jane', 32.625, 'HR'],
       [11, 'Kyle', 25.0, 'Finance']], dtype=object)

In [ ]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:,0])
x
#

array([[0, 'osahon', 29.0, 'Engineering'],
       [1, 'Bob', 32.625, 'Marketing'],
       [2, 'Charlie', 35.0, nan],
       [3, 'David', 42.0, 'Engineering'],
       [4, 'Eva', 30.0, 'HR'],
       [5, 'Frank', 32.625, 'Finance'],
       [6, 'Grace', 27.0, 'Engineering'],
       [7, 'Hannah', 33.0, 'Marketing'],
       [8, 'Ian', 40.0, nan],
       [9, 'Jane', 32.625, 'HR'],
       [10, 'Kyle', 25.0, 'Finance']], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as nm

# First, handle missing values in Department so OneHotEncoder doesn't fail
# Assuming x contains ['S/N', 'Name', 'Age', 'Department']

# Apply OneHotEncoder specifically to column index 3 (Department)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(drop='first', handle_unknown='ignore'), [3])],
    remainder='passthrough'
)

# Transform x
x_encoded = ct.fit_transform(x)

print(x_encoded)

[[0.0 0.0 0.0 0.0 0 'osahon' 29.0]
 [0.0 0.0 1.0 0.0 1 'Bob' 32.625]
 [0.0 0.0 0.0 1.0 2 'Charlie' 35.0]
 [0.0 0.0 0.0 0.0 3 'David' 42.0]
 [0.0 1.0 0.0 0.0 4 'Eva' 30.0]
 [1.0 0.0 0.0 0.0 5 'Frank' 32.625]
 [0.0 0.0 0.0 0.0 6 'Grace' 27.0]
 [0.0 0.0 1.0 0.0 7 'Hannah' 33.0]
 [0.0 0.0 0.0 1.0 8 'Ian' 40.0]
 [0.0 1.0 0.0 0.0 9 'Jane' 32.625]
 [1.0 0.0 0.0 0.0 10 'Kyle' 25.0]]


In [ ]:
#For purchased variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([5, 1, 3, 7, 0, 4, 6, 7, 2, 7, 7])

In [ ]:
#splitting the dataset into the trading set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
#

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import numpy as np

# Assuming x contains ['S/N', 'Name', 'Age', 'Department']
x_features = x[:, 2:4]

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(drop='first'), [1])],
    remainder='passthrough'
)
x_encoded = ct.fit_transform(x_features)

x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=1)

In [ ]:
x_test


array([[0.0, 0.0, 0.0, 1.0, 35.0],
       [0.0, 0.0, 0.0, 0.0, 42.0],
       [0.0, 1.0, 0.0, 0.0, 30.0]], dtype=object)