# **MACHINE LEARNING (LEARNED MODEL)**


AI is bigger concept to create intelligent machines that can simulate human thinking capability and behaviour, whereas, machine learning is an application or subset of AI that allows machines to learn from past data or experiences without being programmed. Machine Learning enables a computer system to make predictions or take some decisions using historical data without being programmed.

Machine Learning is being used in various places such as for online recommended system, for Google search algorithms, Email spam filter, Facebook auto friend tagging suggestions, etc.

Machine Learning is classified into three:
1. Supervised Learning (Classification and Regression)
2. Unsupervised Learning (Clustering and Association)
3. Reinforcement Learning (Robotic)

**How to get dataset for machine learning**

The key to success in the field of machine learning or to become a great data scientist is to practice with different types of datasets but discovering a suitable dataset for each kind of machine learning project is a difficult task.

**What is a dataset?**

A dataset is a collection of data is arranged in some order. A dataset can contain any data from a series of an array to a dataset table. A tabular dataset can be understood as a database table or matrix, where each column corresponds to a particular variable, and each row corresponds to the fields of the dataset. The most supported file type for a tabular dataset is 'Comma Separated Value (CSV).

**Types of Data in a Dataset**
1. Numerical data
2. Categorical data

**Need of Dataset**

Collecting and preparing the dataset is one of the most crucial parts while creating a AI/Machine learning project.

In building machine learning applications, datasets are divided into two parts:

1. Training Dataset
2. Test Dataset

**Data Processing in Machine Learning (ML)**

Data processing is a process of preparing the raw data and making it suitable for a machine learning model.

The Step for data preprocessing includes:

1. Getting the dataset
2. Importing libraries
3. Importing dataset
4. Finding missing data
5. Encoding categorical data
6. Splitting dataset into train and test set
7. Feature scaling

**IMPORT LIBRARIES (MODULES)**

In [ ]:
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt

**Mount the google drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Load the dataset
dataset = pd.read_csv('/content/drive/MyDrive/country.csv')

In [ ]:
#Dispaly the dataset output
dataset

**Extracting dependent and independent variable**

In machine learning, it is important to distinguish the matrix of features(independent variables) and dependent variables from the dataset, there are three independent variables that are country, age, and salary, and one is dependent variable which is purchased.

In [ ]:
#Extracting independent variable
'''To extract the independent variable, we use iloc[] method of pandas library.It is used to extract the required rows and columns from the dataset.'''

x=dataset.iloc[:,:-1].values
x

array([['India', 38, 48000.0],
       ['France', 43, 45000.0],
       ['Germany', 30, 54000.0],
       ['France', 48, 65000.0],
       ['Germany', 40, nan],
       ['India', 35, 58000.0]], dtype=object)

In [ ]:
#Extracting the dependent variable
y=dataset.iloc[:,3].values
y

'''Note:
Extraction of x and y axis is manadatory in machine learning code.'''

'Note:\nExtraction of x and y axis is manadatory in machine learning code.'

**Ways of handling missing data**

The next step of data preprocessing is to handle missing data in the dataset. If our dataset contains some missing data, then it may create a huge problem for our machine learning model. Hence, it is necessary ot handle missing values present in the datasets.

There are mainly two ways to handle missing data:

1. By deleting the particular row (Analytical Model)

2. By Calculating the mean to fill the missing value(Learned Model)

In [ ]:
#Handling missing data
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=nm.nan,strategy='mean')
imputer=imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['India', 38.0, 48000.0],
       ['France', 43.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['France', 48.0, 65000.0],
       ['Germany', 40.0, 54000.0],
       ['India', 35.0, 58000.0]], dtype=object)

**Encoding categorical data**

Categorical data is data which has same categories in our dataset, there are two categorical variable which are country and purchased. Since machine learning model completely works on mathematics and numbers, but in our dataset would have a categorical variable, then it may create trouble while building the model. So it is necessary to encode these categorical variables in to numbers.

In [ ]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x=LabelEncoder()
x[:,0]=labelencoder_x.fit_transform(x[:,0])
x

array([[2, 38.0, 48000.0],
       [0, 43.0, 45000.0],
       [1, 30.0, 54000.0],
       [0, 48.0, 65000.0],
       [1, 40.0, 54000.0],
       [2, 35.0, 58000.0]], dtype=object)

**Dummy Variable**

Dummy variables are those variables which have values 0 or 1. The 1 value give the presence of that variables in a particular column and rest variablle become 0. With dummy encoding, we will have a number of columns eqaul to the number of categorinies. So it will produce three columns having 0 and 1 values.

In [ ]:
#Dummy Variable
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder # Import OneHotEncoder

columnTransformer=ColumnTransformer([('encoder',OneHotEncoder(),[0])],
                                      remainder='passthrough')
x=np.array(columnTransformer.fit_transform(x))
x

array([[0.0, 0.0, 1.0, 38.0, 48000.0],
       [1.0, 0.0, 0.0, 43.0, 45000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 48.0, 65000.0],
       [0.0, 1.0, 0.0, 40.0, 54000.0],
       [0.0, 0.0, 1.0, 35.0, 58000.0]], dtype=object)

In [ ]:
#For purchase variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1])

In [ ]:
#splitting the dataset into the traning set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [ ]:
x_test

array([[-1.        , -0.57735027,  1.73205081, -1.9247976 ,  0.65372045],
       [-1.        ,  1.73205081, -0.57735027, -3.25224423,  0.13074409]])